class Program
{
    
    public static void Main()
    {
        Player player = new Player();
    
        
        //player.AddItem(new Item("Healing Potion100", Effect.BaseEffects["HealInstant100"], "heals 100 instantly", 1)); //stacks fine
        //since Item and Effect ID's  are now generated by their own classes we could use the below method and things should still stack fine
        player.AddItem(new Item("Healing Potion10", new Effect("HealInstant10", 10, EffectTypes.HEALINSTANT, 1), "heals 10 instantly", 1));
        player.AddItem(new Item("Healing Potion10", new Effect("HealInstant10", 10, EffectTypes.HEALINSTANT, 1), "heals 10 instantly", 1));
        player.AddItem(new Item("Healing Potion10", new Effect("HealInstant10", 10, EffectTypes.HEALINSTANT, 1), "heals 10 instantly", 1));
        player.AddItem(Item.BaseItems["Healing Potion10"].Copy()); 
        player.Coins = 200;


        //player.AddItem(new Item("Healing Potion", BaseEffects.HealInstant10, "heals 10 instantly", 1));
        Helper.TitleScreen();
        player.CurrentLocation.Map();
        while (true)
        {
            //enable to force a fight at the start
            //SuperAdventure.Fight(player, new Monster(1, "Goblin", 1, 80, 100));
            player.AskPlayerAction(player);
        }
    }
}
